CLS
SCREEN 13
FOR x = 16 TO 31
COLOR x
LOCATE 12, 1
PRINT "             Welcome to..."
NEXT
CLS
FOR x = 16 TO 31
COLOR x
LOCATE 12, 1
PRINT "           A MHS production..."
NEXT
CLS
FOR x = 16 TO 31
COLOR x
LOCATE 12, 1
PRINT "   Made only for the pupils of KOK..."
NEXT
CLS
FOR x = 16 TO 31
COLOR x
LOCATE 12, 1
PRINT "      When you want to go sky-high"
PRINT "        We've got what you need!  "
NEXT
'CLS
SCREEN 0
LOCATE 2, 1
PRINT "   здддбдбдбдбд©  здддбдддбддбдддбддд©"
PRINT "   Ё  д╢  д╢   цдд╢ д Ё Ё ЁЁЁЁ дд╢ Ё Ё"
PRINT "   цд  Ё Ё ц© задд╢ д Ё Ё ЁЁЁЁ дд╢  д╢"
PRINT "   юдддададыюды   юдддадддаааадддадады"
PRINT
PRINT "              By: Andy Sky"
SLEEP

